[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "humbug"
version = "0.7"
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "certifi",
    "m6rclib",
    "pyside6",
    "qasync"
]

[tool.hatch.build.targets.wheel]
packages = ["src/humbug"]

[tool.pyinstaller]
excludes = ["build", "dist", "*.egg-info"]
